// @generated
// This file is @generated by prost-build.
/// EventCreateInterchainSecurityModule defines the event type emitted when creating a new InterchainSecurityModule.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventCreateInterchainSecurityModule {
    /// unique hyperlane identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// the owner or creator of the ism
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    /// latest state
    #[prost(string, tag="3")]
    pub state: ::prost::alloc::string::String,
    /// the sp1 groth16 verifier key (hex-encoded)
    #[prost(string, tag="4")]
    pub groth16_vkey: ::prost::alloc::string::String,
    /// hash-based commitment to the verifier key used for state transition (hex-encoded)
    #[prost(string, tag="5")]
    pub state_transition_vkey: ::prost::alloc::string::String,
    /// hash-based commitment to the verifier key used for state membership (hex-encoded)
    #[prost(string, tag="6")]
    pub state_membership_vkey: ::prost::alloc::string::String,
}
/// EventUpdateInterchainSecurityModule defines the event type emitted when updating a InterchainSecurityModule.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventUpdateInterchainSecurityModule {
    /// unique hyperlane identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// new state
    #[prost(string, tag="2")]
    pub state: ::prost::alloc::string::String,
}
/// EventSubmitMessages defines the event type emitted after successful message submission.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventSubmitMessages {
    /// unique hyperlane identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// state commitment root used to verify messages (hex-encoded)
    #[prost(string, tag="2")]
    pub state_root: ::prost::alloc::string::String,
    /// list of authorized messages ids
    #[prost(string, repeated, tag="3")]
    pub messages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// InterchainSecurityModule defines the Hyperlane interchain security module (ISM).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InterchainSecurityModule {
    /// unique hyperlane identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// the owner or creator of the ism
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    /// current state 
    #[prost(bytes="vec", tag="3")]
    pub state: ::prost::alloc::vec::Vec<u8>,
    /// the sp1 groth16 verifier key
    #[prost(bytes="vec", tag="4")]
    pub groth16_vkey: ::prost::alloc::vec::Vec<u8>,
    /// hash-based commitment to the verifier key used for state transition
    #[prost(bytes="vec", tag="5")]
    pub state_transition_vkey: ::prost::alloc::vec::Vec<u8>,
    /// hash-based commitment to the verifier key used for state membership
    #[prost(bytes="vec", tag="6")]
    pub state_membership_vkey: ::prost::alloc::vec::Vec<u8>,
}
/// Params defines the zk ism module parameters.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Params {
    #[prost(uint32, tag="1")]
    pub max_header_hashes: u32,
}
/// GenesisState defines the zkism module's genesis state.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenesisState {
    /// list of zk execution isms.
    #[prost(message, repeated, tag="1")]
    pub isms: ::prost::alloc::vec::Vec<InterchainSecurityModule>,
    /// TODO: add messages to genesis state
    /// params is the module parameters.
    #[prost(message, optional, tag="2")]
    pub params: ::core::option::Option<Params>,
}
/// QueryIsmRequest is the request type for the Ism rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
/// QueryIsmResponse is the response type for the Ism rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmResponse {
    #[prost(message, optional, tag="1")]
    pub ism: ::core::option::Option<InterchainSecurityModule>,
}
/// QueryIsmsRequest is the request type for the Isms rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmsRequest {
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::super::cosmos::base::query::v1beta1::PageRequest>,
}
/// QueryIsmsResponse is the response type for the Isms rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmsResponse {
    /// isms is a list of zk execution isms.
    #[prost(message, repeated, tag="1")]
    pub isms: ::prost::alloc::vec::Vec<InterchainSecurityModule>,
    /// pagination defines the pagination in the response.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::cosmos::base::query::v1beta1::PageResponse>,
}
/// QueryParamsRequest is the request type for the Params rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsRequest {
}
/// QueryParamsResponse is the response type for the Params rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsResponse {
    /// params contains the module parameters
    #[prost(message, optional, tag="1")]
    pub params: ::core::option::Option<Params>,
}
/// MsgCreateInterchainSecurityModule is the request type for CreateInterchainSecurityModule.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateInterchainSecurityModule {
    /// creator is the message sender.
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    /// initial trusted state
    #[prost(bytes="vec", tag="2")]
    pub state: ::prost::alloc::vec::Vec<u8>,
    /// the sp1 groth16 verifier key
    #[prost(bytes="vec", tag="3")]
    pub groth16_vkey: ::prost::alloc::vec::Vec<u8>,
    /// hash-based commitment to the verifier key used for state transition
    #[prost(bytes="vec", tag="4")]
    pub state_transition_vkey: ::prost::alloc::vec::Vec<u8>,
    /// hash-based commitment to the verifier key used for state membership
    #[prost(bytes="vec", tag="5")]
    pub state_membership_vkey: ::prost::alloc::vec::Vec<u8>,
}
/// MsgCreateInterchainSecurityModuleResponse is the response type for CreateInterchainSecurityModule.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateInterchainSecurityModuleResponse {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
/// MsgUpdateInterchainSecurityModule is the request type for UpdateInterchainSecurityModule.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateInterchainSecurityModule {
    /// ism identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// proof is the ZK proof bytes (groth16).
    #[prost(bytes="vec", tag="2")]
    pub proof: ::prost::alloc::vec::Vec<u8>,
    /// the public values used for proof verification.
    #[prost(bytes="vec", tag="3")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
    /// the tx signer address
    #[prost(string, tag="4")]
    pub signer: ::prost::alloc::string::String,
}
/// MsgUpdateInterchainSecurityModuleResponse is the response type for UpdateInterchainSecurityModule.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateInterchainSecurityModuleResponse {
    /// new ism state
    #[prost(bytes="vec", tag="1")]
    pub state: ::prost::alloc::vec::Vec<u8>,
}
/// MsgSubmitMessages is the request type for SubmitMessages.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgSubmitMessages {
    /// ism identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// height is the EVM application height associated with the state transition update.
    #[prost(uint64, tag="2")]
    pub height: u64,
    /// proof is the ZK proof bytes (groth16).
    #[prost(bytes="vec", tag="3")]
    pub proof: ::prost::alloc::vec::Vec<u8>,
    /// the public values used for proof verification.
    #[prost(bytes="vec", tag="4")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
    /// the tx signer address
    #[prost(string, tag="5")]
    pub signer: ::prost::alloc::string::String,
}
/// MsgSubmitMessagesResponse is the response type for SubmitMessages.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgSubmitMessagesResponse {
}
/// MsgUpdateParams is the request type for UpdateParams.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateParams {
    /// authority is the address that controls the module (defaults to x/gov unless overwritten).
    #[prost(string, tag="1")]
    pub authority: ::prost::alloc::string::String,
    /// params defines the x/zkism parameters to update.
    ///
    /// NOTE: All parameters must be supplied.
    #[prost(message, optional, tag="2")]
    pub params: ::core::option::Option<Params>,
}
/// MsgUpdateParamsResponse defines the response type for UpdateParams.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateParamsResponse {
}
include!("celestia.zkism.v1.tonic.rs");
// @@protoc_insertion_point(module)